module "aws" {
  count                   = var.platform == "aws" ? 1 : 0
  source                  = "./modules/aws"
  aws_region              = var.aws_region
  cidr_block              = var.cidr_block
  create_dns_record       = var.create_dns_record
  create_networking       = var.create_networking
  dns_record_name         = var.dns_record_name
  dns_record_ttl          = var.dns_record_ttl
  dns_zone_name           = var.dns_zone_name
  ghidra_install_path     = var.ghidra_install_path
  ghidra_name             = var.ghidra_name
  ghidra_server_config    = var.ghidra_server_config
  ghidra_server_log_level = var.ghidra_server_log_level
  ghidra_repo_path        = var.ghidra_repo_path
  ghidra_uri              = var.ghidra_uri
  ghidra_version          = var.ghidra_version
  ghidra_version_map      = var.ghidra_version_map
  initial_java_heap_size  = var.initial_java_heap_size
  instance_type           = var.instance_type
  max_java_heap_size      = var.max_java_heap_size
  repo_device_name        = var.repo_device_name
  repo_volume_size        = var.repo_volume_size
  repo_volume_type        = var.repo_volume_type
  s3_backup               = var.s3_backup
  s3_bucket_name          = var.s3_bucket_name
  subnet_id               = var.subnet_id
  vpc_id                  = var.vpc_id
}