# Eventually should split this into disparate jobs
on:
  push:
    branches:
      - linode
  pull_request:
    branches:
      - master
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v3
    with:
      go-version: '>=1.19.0'
  - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  - name: "Run Terratest"
    env:
      TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
    run: |
      cd terratest
      go test -v -timeout 30